### ISSUE TITLE
Action for deactivating the Internet connection

### ISSUE THREAD

**Issue by curio77** [ajalkane/profilematic#24]
Relaying from a user without a github account:

I'd appreciate an option for deactivating the Internet connection (corresponding to what happens when toggling the Internet      connection in system-level “Settings” → “Internet”)?   I'd envision this similar to Bluetooth, allowing me to  conserve some additional energy when Internet is not needed.

**Comment by ajalkane** [comment]
Seems not to be possible. At least I haven't found any obvious way to do this from 3rd party applications using public harmattan APIs. I'm closing this issue for now, but am willing to take another look if someone finds a way to do this.
