### ISSUE TITLE
Cosmetic: Shortcut icon label

### ISSUE THREAD

**Issue by curio77** [ajalkane/profilematic#27]
Relaying from a user without a github account:

Would it be possible to change the application name as used with the app's shortcut icon such that it is not abbreviated by “…” (or at least written with the same capitalization as the official name)?  As it is now, _ProfileMatic_ is the only app on my device whose short cut name needs abbreviating.

**Comment by ajalkane** [comment]
Hmm... works for me. Shows as "ProfileMatic" in menu without any dots. Do you have any tweaks installed? A screenshot maybe?

**Comment by curio77** [comment]
It's about the shortcut icon on the “desktop”, see this screenshot for clarification:

http://imageshack.us/photo/my-images/814/screenshotsv.png/

“profilematic” appears to be just slightly too wide.  Of course, modifying the name displayed there will likely also alter the name displayed elsewhere, which is probably not desirable.  Neither is a change of name, I guess. ;-)

**Comment by ajalkane** [comment]
There is something wrong with your installation. In your picture the application is written "profilematic" without capital letters, it should be "ProfileMatic". See this screenshot:

http://www.kolumbus.fi/~ks2877/profilematic/profilematic_in_menu.png

**Comment by ajalkane** [comment]
Seems like your problem was a real one... I found the culprit and it happens only with US language. It will be fixed in 1.7.0.
