### ISSUE TITLE
Action requests

### ISSUE THREAD

**Issue by andreaswallberg** [ajalkane/profilematic#30]
Thanks for an absolutely wonderful app.

 I have two feature requests that I would gladly give a donation for if they were implemented, both of them actions:
- Connect to specific bluetooth device

Scenario: when I come home (detected by automatically connecting to my home wlan), I would like the phone to try to connect to my bluetooth speakers in the kitchen.
- Start/restart application

Scenario: some apps reload data only when started or when manually refreshed. One such app is Podcatcher. Again, I would like to launch podcatcher when I connect to my home network. This can be done by executing a custom cli commands as an action but it would be nice to be able to select the app in question visually.

**Comment by ajalkane** [comment]
I created two separate issues from these. Closing this one.
